### ISSUE TITLE
Collections ignored

### ISSUE THREAD

**Issue by dferber90** [dferber90/eslint-plugin-meteor#85]
This `.eslintrc.yml` configuration seems to no longer work after eslint 1.10

```yaml
settings:
  meteor:
    collections:
      - Businesses
      - ...
```

Results in
```
/path/to/file.js
  18:28  error  "Businesses" is not defined  no-undef
```

It works in the tests, but not in real applications!?
